### ISSUE TITLE
How to get the role of a user?

### ISSUE THREAD

**Issue by alex996** [JosephSilber/bouncer#108]
Is there a way to get the role of the current user? Ideally, I am looking for something similar to `$user->getAbilities()`, but in this case it would be `$user->getRole();`. Does Bouncer support this? Thanks

**Comment by Arcesilas** [comment]
Did you try `Auth::user()->roles`?

**Comment by JosephSilber** [comment]
Yes. To get the roles for a user, simply call `$user->roles`.

If you only want the names for the roles, you use `pluck` on the relationship:

```php
$roles = $user->roles()->pluck('name');
```

**Comment by dhcmega** [comment]
Hi
How this relation should be created? Pivot table user_role doesn't exist. Thanks.

**Comment by Arcesilas** [comment]
There is indeed no `user_role` table because there is an `assigned_roles` which uses polymorphism to assign roles: https://github.com/JosephSilber/bouncer/blob/master/migrations/create_bouncer_tables.php#L40

Roles can be assigned to not only `User` model (See https://github.com/JosephSilber/bouncer/issues/43#issuecomment-175668400)
