### ISSUE TITLE
Disable cache during testing

### ISSUE THREAD

**Issue by bkuhl** [JosephSilber/bouncer#129]
Is there a way to disable the cache?  I have some tests where I'm performing assertions and currently have `Bouncer::refresh();` in there to get the cache to reset.  Took be a while to figure out the cache was why my test was failing.  It'd be great if while in the `testing` environment the cache was disabled.

Here's an example:

```php

    public function canDeletePlayer()
    {
        $player = Player::first();

        $this->assertTrue($player->guardian->is(Role::GUARDIAN));

        $this
            ->visit('/admin/players/'.$player->id)
            ->press('Delete Player')
            ->see('Player has been deleted');
        
        Bouncer::refresh();
        $this->assertTrue($player->guardian->isNot(Role::GUARDIAN));
    }
```

**Comment by JosephSilber** [comment]
I don't think it makes sense to automatically disable caching when testing, because you may want to include the cache clearing in your tests.

If you personally do want to disable the cache, you can use the `dontCache` method ([just added](https://github.com/JosephSilber/bouncer/commit/982d629679ebb81bf436482f279109d9bda63583)) to disable it yourself:

```php
Bouncer::dontCache();
```

You can either put that in the setup of your base test class, or in your service provider with a testing conditional:

```php
if ($this->app->runningUnitTests()) {
    Bouncer::dontCache();
}
```

**Comment by bkuhl** [comment]
That's a great point, thanks for including this method.

**Comment by ziming** [comment]
Should it be in the setUp() method or the constructor of TestCase?

A little confused here
