### ISSUE TITLE
How do i make it possible to check for ability based on wildcard charracter?

### ISSUE THREAD

**Issue by mramitict** [JosephSilber/bouncer#144]
Is it possible to have a wildcard for @can. Example. I have 4 permissions: person-view, person-update, person-delete, person-create. I want to use @can('person-*') to see if that user has any of the permissions listed?

**Comment by Procu** [comment]
you should use policies to check permissions

**Comment by mramitict** [comment]
Well! then I didn't understand the use of bouncer. Isn't both a complementary of each other?

**Comment by Procu** [comment]
@can('manage', Person::class)
Policy will tell you that user can or cannot manage entities of type Person

But how we will know that?
Policy should check via Bouncer is user permitted to create, edit, view and delete that type o entities or a specific entity

**Comment by JosephSilber** [comment]
`@can('person-*')` would never work, because there can be an infinite amount of abilities, so there's no way to know just by looking at the list of granted abilities.

Can you explain more your use-case for this? Where do you find yourself having to run such a check?

**Comment by mramitict** [comment]
You are absolutely right @JosephSilber.

I want to use it with multiple roles such as Admin, Manager, Team leader and Cleaner where [**person-list, person-create, person-delete and person-update**] is an ability. Case is,  Admin and manager is allowed to do all operation on Person model while Team leader is allowed to list the data of Person model and  Cleaner is not allowed to do anything on it. So to allow these abilities for the model lots of insert operation is being performed, I just wanted to reduce it to single one for Admin and manager. When I create a user with any role, it takes lots of time to prepare a setup for that.

Thanks

**Comment by JosephSilber** [comment]
I'm a little confused. Are we talking about granting the abilities or checking them?

**Comment by mramitict** [comment]
My question was always about,  to check the ability of kind **person-*** within the constructor of controller, while granted abilities should be like **[person-list, person-create, person-delete and person-update]** with authorize method of controller. 

By the way i got your point by your earlier statement. Thanks for helping me out @JosephSilber

**Comment by JosephSilber** [comment]
To clarify:

1. To grant all abilities on a model, use the `toManage` method:

    ```php
    Bouncer::allow($user)->toManage(Person::class);
    ```

    This will give the user all abilities on the `Person` class.

2. To check all abilities in the controller constructor, use the `authorizeResource` method:

    ```php
    $this->authorizeResource(Person::class);
    ```

    For more information, read my blog post: [Gate and authorization improvements in Laravel 5.3](https://josephsilber.com/index.php/posts/2016/08/03/authorization-improvements-in-laravel-5-3).

**Comment by dschreij** [comment]
Is the 

~~~
@can('manage', Person::class)
~~~

that @Procu stated a valid call within Bouncer? I mean, I know that it will work without errors, but will it return `true` if the user has all CRUD permissions on the given model, and `false` if he or she doesn't (e.g. cannot perform at least one of the CRUD actions?). 
Phrased differently, what is the counterpart can() call of 
~~~
Bouncer::allow($user)->toManage(Person::class);
~~~
that checks if the user has management rights on this class?

**Comment by dschreij** [comment]
> @can('manage', Person::class)
> Policy will tell you that user can or cannot manage entities of type Person
> 
> But how we will know that?
> Policy should check via Bouncer is user permitted to create, edit, view and delete that type o entities or a specific entity

I understand that the Policy and Bouncer systems work hand in hand, but it still isn't clear to me which one has precedence, or how to make them work smoothly together. Initially I thought I had to place the `$user->can()` calls that use Bouncer/Gate to check for permissions inside the policy methods, but that resulted in infinite loops, so it probably wasn't the right way to go...

Searching further, I have come to understand that Bouncer is currently capable enough to take over all the tasks that you would normally use the Policy object for (especially now you can manage ownership with the toOwn() method). Is there any reason to (or can you give an example use-case where to) still use Policy objects? In which situations would Bouncer fall short and would you use a Policies?

**Comment by JosephSilber** [comment]
@dschreij

1. `@can('manage', Person::class)` is definitely **not** what you want here.

    That would simply check if the user has the `manage` ability, which would mean that it has been granted with something like this: `Bouncer::allow($user)->to('manage', Person::class)`. Clearly something else entirely.

2. You generally don't want to check if a user has all abilities. You usually check them one by one, as you need them. Laravel's controllers have the handy `authorizeResource` method, which will check each REST action for its corresponding ability.

    For more information, I would once again refer you to my blog post on this manner: [Gate and authorization improvements in Laravel 5.3](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3).

3. If you find yourself in a situation where you _do_ need to know if the user has been granted all abilities on a model, you can use the magic `*` ability, which is what the `toManage` method uses under the hood.

    I'd strongly discourage this (since it relies on an implementation detail, and is just generally not something you want to check for directly), but if you do want to, here's how you'd do it:

    ```php
    $user->can('*', Person::class);
    ```

4. Regarding documentation, they are definitely lacking in some areas. Documentation is actually the only reason Bouncer is still in beta. I just haven't had the time yet to fully finish it off.

**Comment by dschreij** [comment]
Thanks for your thoughts Joseph.

1. I did not really want to check if a user has *all* permissions for a certain resource, I wanted to check if he or she has *any*. My use case is that I want to hide a link in the navbar to the management page of a certain resource if the user has no permissions to create, view, update or delete records of this resource anyway. If the user does have at least one of these permissions , the link should be shown (and the buttons for actions which the user is not permitted to perform will be hidden on the page that lists the resource records, so that is where the specific permission checks happen). There currently really isn't a way to do this with a short expressions as far as I can see. I have to do this in blade like this (using the person class as an example):

~~~ php
if( Auth::user()->can('view', Person::class) or Auth::user()->can('create', Person::class) or Auth::user()->can('update', Person::class) or Auth::user()->can('delete', Person::class)){
    // Show the link
}
~~~

Am I right that there currently is no shorthand for this? e.g.

~~~ php
if( Auth::user()->can(['view','create','update','delete'], Person::class)){
    // Show the link
}
~~~

or even

~~~ php
@can(['view','create','update','delete'], Person::class)
     // Show the link
@endcan
~~~ 

I have currently solved this by creating a function in my User model that checks if the user at least has one of the CRUD permissions for a given model, and that works fine for now:

~~~ php
$user->hasSomeCrudPermissions(Person::class);
~~~

2. I have read your blog; it was very interesting and I am already using the authorizeResource() method where applicable!

3. I think for this situation I would create another method on the user model that explicitly checks for ['view','create','update','delete'] permissions on the given model, e.g.

~~~ php
$user->hasAllCrudPermissions(Person::class);
~~~

I haven't bumped into this case though.

4. If you need help, let me know. I have learned a lot about bouncer by just giving it a go (trial and error). The only thing that is still unclear to me is how Bouncer works together with Policies, and which get precedence over the other (it seems that Policies have the upper hand?). It also seems to me that you can do anything with Bouncer that you would normally do with policies (e.g. check for ownership), am I correct? Could Bouncer completely replace the Policy system?

**Comment by JosephSilber** [comment]
1. If you give a user create/update/delete permissions, you probably also give them viewing permissions, no? Do you have a case where you'd let someone create/update/delete records, but not view them? I don't think that makes much sense.

    If that's the case, a simple `@can('view', Person::class)` should do.

2. Glad you read it!

3. You can definitely add a `hasAllCrudPermissionsFor` to your user model:

    ```php
    public function hasAllCrudPermissionsFor($model)
    {
        $abilities = ['view', 'create', 'update', 'delete'];

        return collect($abilities)->every(function ($ability) {
            return $this->can($ability, $model);
        });
    }
    ```

    ...but I don't think this makes sense in Bouncer core.

4. Documentation is always a tricky matter to get help with. Different people write differently, and you do want the documentation to sound like it speaks in a single voice.

    If you want to try and keep to the current style, you can try to create a PR.

**Comment by dschreij** [comment]
1. You're right. I was actually working on this matter at the moment, and already found out my approach didn't really make much sense.

3. Thanks for the concise function. It's better than mine ;)

4. I understand. Maybe I can contribute in another way in the near future, by for instance writing a short tutorial on my blog for a simple use case with Bouncer.
