### ISSUE TITLE
Is it possible to retract all roles from a user / collection of users?

### ISSUE THREAD

**Issue by alex996** [JosephSilber/bouncer#160]
I'd like to know how to retract all roles from a collection of users, as well as from a single user. I can see that `retract()` accepts a `Role` or a string, but not an array. Besides, I found that the wildcard `'*'` does not work with `retract()` either. What's the right way to accomplish this?

**Update**

Just realized this could be done purely with Eloquent: `$user->roles()->sync([])`. I feel this is somewhat hacky though. Any better solutions?

**Comment by JosephSilber** [comment]
User roles in Bouncer is simply a `BelongToMany` relationship. Calling `detach` is the way to go:

```php
$user->roles()->detach();
```

**Comment by dhcmega** [comment]
@JosephSilber I tried:

`$user->roles()->detach();`

and (for a user with id 105) sadly the query ran was:

`delete from `assigned_roles` where `entity_id` = 105`

But there was also an admin with id 105.
This affected more than 100 admins by now, I have just fixed it.

Is this because I have an error on my relation?
This is my User relation:

```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function roles()
    {
        return $this->belongsToMany(\Silber\Bouncer\Database\Role::class, 'assigned_roles', 'entity_id')->where('entity_type', 'App\Models\User');
    }
```

Thanks!
