### ISSUE TITLE
Am I getting it right? (Documentation/Support)

### ISSUE THREAD

**Issue by dhcmega** [JosephSilber/bouncer#201]
Hi
Please let me know if I get it right.

I can give abilities to a User or to a Role.

So, tables:
roles: List of roles. What is level?
abilities: ability + optional entity or (entity+id). This gives ability over whole Class or model instance, that can be assigned to a role or a user?

These are more complicated:
assigned_roles: role_id + (entity+id). Is this for giving roles to an entity other than User::class? Or is this just por linking Users with Roles?
permissions: ability_id + (entity+id). Does this link roles to abilities? Why does it need an entity column? Can it link a user directly to a ability, without using roles?

How should I solve this situation:
admin: has manage abilities over Post::class.
manager: has manage abilities over Post::class.
operator1: has X abilities over Post::class.
operator2: has Y abilities over Post::class.

Should I?:
```
Bouncer::allow($admin_user)->toManage(Post::class);
Bouncer::allow($manager_user)->toManage(Post::class);
Bouncer::allow($operator1_user)->to('ability1', Post::class);
Bouncer::allow($operator2_user)->to('ability2', Post::class);
```

And then in Blades use:
```
@can( XXX , Post::class)
Show button to Post CRUD
@endcan
```

How can I ask if the user has any role related with Post::class, so I show the user the CRUD button for all the allowed models? Any user with a role involving a Post model should be able to access the CRUD section.

Thanks!

Edit1:
I think I will just create 'view-post-menu' ability, and assign it to all the needed roles.

**Comment by dhcmega** [comment]
Hi
I'm still trying to understand a few tricky things about Bouncer. It will be a very important part of the system and I would like to understand as muchas as I can.

I will try to figure them out, but can any one help me levels? I have given level values to roles, I have given 10 to Root role, 20 to admin and 30 to the simplest user. After this, all users have all abilities. How come? How does level suppose to work?

Based on the query, it seems that as long as there is a role with a higher level, abilities of the higher level will be granted to the lowest level? This this for inheriting abilities?
This way I can only have one line of linage? because a role will inherit all the abilities of the roles with higher level?

select * from `abilities` where exists (select * from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = '0' and `permissions`.`entity_type` = 'roles' and (exists (select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where assigned_roles.role_id = roles.id and `assigned_roles`.`entity_type` = 'App\User' and `users`.`id` = '1') or `level` < (select max(level) from `roles` where exists (select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where assigned_roles.role_id = roles.id and `assigned_roles`.`entity_type` = 'App\User' and `users`.`id` = '1')))) or exists (select * from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`entity_type` = 'App\User' and `permissions`.`forbidden` = '0' and `users`.`id` = '1')

I hope I get some light on this.

Thanks!

**Comment by JosephSilber** [comment]
> Based on the query, it seems that as long as there is a role with a higher level, abilities of the higher level will be granted to the lowest level?

Correct.

> a role will inherit all the abilities of the roles with higher level?

That's how it currently works. I'm actually pondering removing this feature, since 1) people are confused by it 2) it adds a lot of complexity to the package 3) is not really needed so much now that we have broader abilities and the ability to forbid abilities granularly.

Can you explain to me how you're actually using these levels, and why?

**Comment by dhcmega** [comment]
@JosephSilber
Thanks for taking the time to respond.
At first, my idea was that level was a kind of rank to determine hierarchy between roles. For example a role with higher rank would be able to update/create roles or update/create users with roles of the same or lower level, but not higher. I guess that I should be able to achieve the same with abilities.
I think that the idea of inheritance is not bad, but risky.
The confusion might be related with the lack of information about this subject in the docs.
I'm not native english speaker, but if it's useful I can try to come up with a simple explanation to add.
Let me know if I can help with this.
PS In case you wonder, I'm a Spanish speaker.

Thanks!

**Comment by JosephSilber** [comment]
@dhcmega again, I'm trying to understand whether you have an actual need for the current implementation of Bouncer's levels.

What are you using the levels for, and why would you not be able to do it without it?

**Comment by dhcmega** [comment]
@JosephSilber I'm not using the level feature.
I tried to use it as a way to know if a role has higher hierarchy over another, but it's not how it works. And I will not use it as a way to inherit abilities.
For inheritance I would use something where a role inherit from other roles, like Admin inherit from Operator + Seller + extra ability, for example.

**Comment by JosephSilber** [comment]
> For inheritance I would use something where a role inherit from other roles

@dhcmega how will your roles inherit from one another?

**Comment by dhcmega** [comment]
@JosephSilber I'm sure I fully understand the question

How as in concept/idea? You create roles, and instead of create roles with all the same abilities plus an extra few, you inherit from 1 or more roles and add the extra abilities that might be needed.

How as in implementation? I don't know, one way could be creating a new table in which you specify the role id and all the role ids from which inherit from. Other way could be to have level as an array field in which there is a list of all the roles to inherit from.

What do you think?

**Comment by JosephSilber** [comment]
Ah now I get it. I thought you were saying that you already have a way to do it.

So no. Currently roles can't have a complex hierarchy. It's one linear line. But even that is probably not long-lived. I don't see the point, and no one has been able to properly articulate a need for it.

**Comment by michaeljberry** [comment]
@JosephSilber As far as a complex hierarchy, I built a system a few years ago outside of Laravel, that used the [OWASP RBAC library for heirarchical roles](https://github.com/OWASP/rbac). The application initially didn't need more than one line, however, then other departments requested that their systems be updated and rather than creating a new app just for them, I extended the application to include them. The Quality department had their own section, the Quoting department had their own and the Engineering department had their own also. 

Now as far as the roles were concerned, there was no need for the Engineering manager to access to the Quality department's information, however, the Quality manager did need access to the Engineering department's information (specs, CAD drawings, blueprints, etc.). So there was one line of roles for Engineering (Manager, Team Lead, Engineer) along with respective permissions/abilities and another for Quality (Manager, Team Lead, Inspector). However, because the Quality Manager needed access to the Engineering information, the role of Quality Manager also received the Engineering Manager permissions including subordinates' permissions.

Would I be able to implement a similar role structure within Bouncer as I needed in that app? The roles actually extended all the way up to the President of the company, so he could drill into each department if needed, but each department's roles/permissions were for the most part independent of the other departments.

Would that scenario be implemented in Bouncer as such:

    /**
    * Create and assign abilities to roles
    */

    Bouncer::allow('president')->to('approve-raises');
    Bouncer::allow('engineering-manager')->to('approve-quotes');
    Bouncer::allow('quality-manager')->to('scrap-part');

    /**
    * Assign users to roles
    */

    Bouncer::assign('president')->to($user); // $user_id of president

    Bouncer::assign('engineering-manager')->to($user); // $user model of president
    Bouncer::assign('engineering-manager')->to($user); // $user model of engineering manager
    Bouncer::assign('engineering-manager')->to($user); // $user model of quality manager

    Bouncer::assign('quality-manager')->to($user); // $user model of quality manager
    Bouncer::assign('quality-manager')->to($user); // $user model of president

And then to check permissions in the views:

    @if($user->isAn('president'))
        
    @endif

It doesn't seem to be hierarchical though. To add an `engineer` role under `engineering-manager` with the permission of `access-blueprints`, would I need to assign that new role to the `president`, `engineering-manager` and `quality-manager` users?

    /**
    * Create Engineer role with access-blueprint ability
    */

    Bouncer::allow('engineer')->to('access-blueprints');

    /**
    * Allow President, Engineering Manager, Quality Manager and Engineer
    * to access newly created Engineer role with assigned ability
    */
    Bouncer::assign('engineer')->to($user); // $user model of president
    Bouncer::assign('engineer')->to($user); // $user model of engineering manager
    Bouncer::assign('engineer')->to($user); // $user model of engineer
    Bouncer::assign('engineer')->to($user); // $user model of quality manager

Is that how I would manage the roles/abilities/user relationships within Bouncer, or is there an easier way? 

OWASP's RBAC worked with what they calls 'paths'. I could create the same within their library like this (this isn't complete, but gets the gist across): 

    /**
    * Create President, Engineering Manager and Engineer roles
    */

    $rbac->Roles->addPath('/president/engineering_manager/engineer');

    /**
    * Create Quality Manager and Inspector roles. President was already created.
    * President will now inherit all permissions assigned to Quality Manager  
    * and Inspector as soon as they're assigned.
    */

    $rbac->Roles->addPath('/president/quality_manager/inspector');

    /**
    * Assign permissions
    */
    
    $rbac->Permissions->assign($presidentUserId, 'approve-raises');
    $rbac->Permissions->assign($engineeringManagerUserId, 'approve-quotes');
    $rbac->Permissions->assign($engineerUserId, 'access-blueprints');
    $rbac->Permissions->assign($qualityManagerUserId, 'scrap-parts');

    /**
    * Assign roles to users
    */

    $rbac->Users->assign('president', $presidentUserId);
    $rbac->Users->assign('engineering-manager', $engineeringManagerUserId);
    $rbac->Users->assign('engineering', $engineerUserId);
    $rbac->Users->assign('quality-manager', $qualityManagerUserId);

I don't want to compare Bouncer with OWASP's because that'd be apples to oranges. I'm just wondering how to implement this sort of hierarchical roles within Bouncer since I'm working on an app in Laravel that requires similar role/permission inheritance.

Thanks in advance!
