### ISSUE TITLE
Middleware for roles?

### ISSUE THREAD

**Issue by acidjazz** [JosephSilber/bouncer#205]
As I'm learning how to use bouncer I noticed there was no docs/example on checking for a role as a middleware, I did find I can use "can" for abilities:

```php
Route::middleware('auth')->group(function() {
  Route::middleware('can:access-control')->group(function() {
    Route::get('/user/{user}', 'UserController@get');
    Route::get('/users', 'UserController@list');
  });
});
```

But I don't see a way to wrap this around a specific role.. is there any reason why? @JosephSilber I noticed in previous issues you specified it was anti-pattern, maybe could you elaborate a bit more on that?

**Comment by JosephSilber** [comment]
Here's a quote from [the docs](https://github.com/JosephSilber/bouncer#checking-a-users-roles):

> **Note**: Generally speaking, you should not have a need to check roles directly. It is better to allow a role certain abilities, then check for those abilities instead. If what you need is very general, you can create very broad abilities. For example, an `access-dashboard` ability is always better than checking for `admin` or `editor` roles directly.

A role is simply an easy way to grant a bucket of abilities to a given user. But at the end of the day, what you're checking is whether the user can perform a given action. Reaching down and actually checking for the user's role is basically relying on an implementation detail.

If needed, create broader abilities for your users, and check for that directly.

BTW, in your case, what you really want to do is allow a user to handle all permissions on users:

```php
Bouncer::allow($user)->toManage(User::class);
```

Then, instead of using a middleware, [use the `authorizeResource` method](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3) in your controller's constructor:

```php
class UserController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class);
    }
}
```

This will ensure that the proper ability will be checked for each method in the controller.

For more information, read [**Gate and authorization improvements in Laravel**](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3)
