### ISSUE TITLE
How to get all abilities restricted to a specific model instance 

### ISSUE THREAD

**Issue by Kane-One** [JosephSilber/bouncer#206]
After restricting abilities to a specific model instance by doing like this
`Bouncer::allow($user)->to('edit', $post);`
`Bouncer::allow($user)->to('delete', $post);`
...... ......
how can i get all these abilities?

**Comment by rjvandoesburg** [comment]
Do you mean something like this: https://github.com/JosephSilber/bouncer#getting-all-abilities-for-a-user

**Comment by Kane-One** [comment]
@rjvandoesburg nope. i don't want to retrieve all abilities for a user. instead, i only want to get abilities to a certain model instance for a user.

**Comment by flick36** [comment]
`Ability::where('entity_type', $model)->get()`

**Comment by JosephSilber** [comment]
```php
$abilities = Bouncer::ability()->forModel($post)->get();
```

This will also get general abilities for the model that have been granted with:

```php
Bouncer::allow($user->to('view', Post::class);
```

If you only want to get abilities strictly for this model, set the `$strict` flag to `true`:

```php
$abilities = Bouncer::ability()->forModel($post, true)->get();
```

**Comment by fraparisi** [comment]
When I use `$abilities = Bouncer::ability()->forModel($post, true)->get();` on a model class that i own it doesn't return any abilities. It is possible to retrieve abilities for the model that owned?

**Comment by JosephSilber** [comment]
Owned abilities are not granted per model. They're an ownership type of ability.

You can query for them:

```php
$ownershipAbilities = Bouncer::ability()->where([
    'entity_type' => Post::class,
    'only_owned' => true,
])-get();
```

But I'm not sure it'll help you much.

**Comment by fraparisi** [comment]
I've done in a similar way in the meanwhile... i'm using `$user->getAbilities()->where('entity_type', get_class($this))`; on a eloquent model to retrieve abilities that user have on the model
I'm trying to make two different roles, one can view all (call it viewer) and one can view only model that own (call it external, in this case own means that model belong to the same group of users). Because we are using angular as frontend, i'm trying to include in the response object also the abilities that the user has on this particular object and the only way i find to make this is check if the model is owned by the user in case the use is external using `Models::isOwnedBy($user, $this)` and then return abilities. I don't know if exists a better way to do this.
Sorry for some poor English

**Comment by JosephSilber** [comment]
That's correct.

**Comment by JosephSilber** [comment]
> Because we are using angular as frontend, i'm trying to include in the response object also the abilities that the user has on this particular object

Don't check these things directly in the database. To determine whether the user has a set of abilities, check it though the gate (or [Bouncer's pass-through methods](https://github.com/JosephSilber/bouncer#authorizing-users)):

```php
$abilities = collect(['view', 'update', 'delete']);

$abilities = $abilities->flip()->map(function ($_, $ability) use ($post) {
    return Bouncer::allows($ability, $post);
});
```
