### ISSUE TITLE
Delete abilities associated when a resource is deleted?

### ISSUE THREAD

**Issue by flick36** [JosephSilber/bouncer#212]
I think this is not implemented but when you do something like:
``` 
Bouncer::allow($user)->to('edit', $post);
``` 
and then later on you delete the `$post` how do you delete the abilities associated to that `$post`? shouldn't it delete them by default? 🤔

**Comment by JosephSilber** [comment]
If you want this, it has to be manually set up on each entity. Listen to the `deleted` event, and delte the abilities.

**Comment by flick36** [comment]
Ok, thank you! one las question 🙈 Is it possible to have a sync method for the role to sync the users? something like 
```
Bouncer::sync($role)->users($users);
```
and for the abilities would be nice to 😋

**Comment by JosephSilber** [comment]
@flick36 you can use [Eloquent's `sync` method](https://laravel.com/docs/5.5/eloquent-relationships#updating-many-to-many-relationships) for that:

```php
$role->users()->sync($users);
```

**Comment by flick36** [comment]
Thank you very much @JosephSilber Awesome package!

**Comment by JosephSilber** [comment]
Just added [a new `bouncer:clean` command](https://github.com/JosephSilber/bouncer/commit/c4968a1ffbe988425191976aa18b3a4ed8b8f041), which will delete unused abilities.

There are two flags that you can pass it:

1. `--orphaned` - delete abilities that are not assigned to anyone. For example:

    ```php
    Bouncer::allow($user)->to('edit', $post);
    Bouncer::disallow($user)->to('edit', $post);
    ```
    
    At this point, the edit post ability has been orphaned, it'll get deleted.

2. `--missing` - delete abilities whose models have gone missing:

    ```php
    Bouncer::allow($user)->to('edit', $post);

    $post->delete();
    ```
    
   Since the post no longer exist, the ability is of no use anymore, so it'll get deleted.

If you don't pass it any of the flags, it will delete both types of abilities.

If you want this to run automatically, add it to [your console kernel's schedule](https://laravel.com/docs/5.5/scheduling#defining-schedules):

```php
$schedule->command('bouncer:clean')->daily();
```

**Comment by flick36** [comment]
Awesome!! very much appreciated!
