### ISSUE TITLE
Don't assume table names

### ISSUE THREAD

**Issue by jonagoldman** [JosephSilber/bouncer#22]
Is it possible to move relationship table names to a config file?
This can prevent name collisions and also allow to maintain the same naming conventions used for database tables in an app.

**Comment by JosephSilber** [comment]
I would rather not introduce extra config settings.

If you want to change the default table names, [extend the built-in models](https://github.com/JosephSilber/bouncer/releases/tag/v0.0.22).

**Comment by Arcesilas** [comment]
It does not allow to override pivot tables names : user_roles, user_abilities and role_abilities... which I think was Jona's original request ^^

Diggind a bit further, I found that it's actually as easy as "extending" `HasRolesAndAbilities` trait and overriding appropriate methods.

**Comment by jonagoldman** [comment]
@JosephSilber So I need to extend every model just to change the table relationship name? Can I ask why you don like config files?

**Comment by JosephSilber** [comment]
Changing the table names in the migration is the easiest of them all. You own the migration file. It is simply copied from the bouncer package into your migrations directory. Once it's there, you can make any changes you want to it.

As to configs: I dislike them because they add complexity to the system. Every config value you add to a system means there's more variance introduced to it. [Look at the amount of changes needed throughout the codebase](https://github.com/JosephSilber/bouncer/commit/a13957cc72b8af1d516678a4933d4641a5778bb2) to allow extending the built-in models.

Not always are the costs apparent at the time the configuration is introduced. Usually, the introduction of a config value is quite simple. It is later down the line that you start paying interest on those changes.

If there's something that the majority of users may want to configure (or even a healthy chunk of users), I do give it some extra thought. Changing relationship table names does not fit this criteria. For the vast majority of users, the default is perfect.

And for those that want to change it, that's possible too. Without configuration.

**Comment by jonagoldman** [comment]
I understand. I am using Laravel's default naming convention for relationship tables, which is the singular name for each table joined with an underscore. For example 'users' - 'abilities' => 'user_ability'. I will fork and made those changes. Thanks.

**Comment by Arcesilas** [comment]
About configuration, I consider that Cache needs configuration, since you may change Cache engine, move it to an independant server, or a third-party service, etc. As for Database : your application may evolve and require more than one server, or a cluster, etc. Tables names are not supposed to change in any case. Or this means you are refactoring your entire application, which is a specific case and it's no more configuration.
Therefore, I think, like @JosephSilber that not only it's more complexity, but it's not relevant for this precise case.

**Comment by jonagoldman** [comment]
I don't agree. The package must give you the freedom. You are not supposed to change your app to meet the package constrains.

But let me just give you a few examples:

spatie/laravel-permission (**200+** stars on GitHub): 
https://github.com/spatie/laravel-permission/blob/master/resources/config/laravel-permission.php

Zizaco/entrust (**2200+** stars on GitHub)
https://github.com/Zizaco/entrust/blob/master/src/config/config.php

**Comment by Arcesilas** [comment]
You say we are not supposed to change our app to meet the package constraints... I don't agree :)
You seem to consider that the package must be flexible enough to comply to all needs of anyone in any case. I consider that the package brings you tools. If you have to change your habits to use them, so be it. The package is part of the foundation, just like Laravel (note that they are both at the same level in the same `vendor` directory). Your app is what you actually write, modify, according to all requirements. You decide to use a package, you have to deal with its requirements. Or you use another one, or you fork it and modify it, or write your own. I understand that a package should give freedom in usability (it's part of what makes its success), but currently, the package lets you override the models names, tables names. You don't like the way you have to do it, that's another problem :p 

The fact that some popular packages use configuration file for flexibility does not mean it is the absolute truth. Over the past, osCommerce was one of the most used e-commerce solution. Have you ever seen any portion of its code ?

When I first read about Laravel Policies, I did not understand why they had to be source coded. Then, I realized it's the same problem we have here : what will change and what will not ? When you write an app, some roles won't change at all. Admins will always have almost all permissions, whereas users will only be able to edit their own data. When you write YOUR app, which meets YOUR requirements. But when you write an application project you wish people install for their needs, you need more flexibility. However, some roles will not change. But you may want to add new roles dynamically, with specific permissions. Because on your forum, you want to have specific users class who can do this very special action that nobody else needs on their own forum.

It's the same here : you require different tables names, you can change them by extending classes and a trait. That's the way Laravel works. I don't see a case where anyone who installs an application (such as Wordpress, a CMS or whatever) and need to change the tables names. It just does not make sense. Though, when you install such an application, you may need to change the cache engine, the port of memcache, you actually need to specify database host, username, etc.

**Comment by JosephSilber** [comment]
@jonagoldman I see that I've miscalculated how important this is; I've been getting a lot of requests for this lately.

I've now implemented it in https://github.com/JosephSilber/bouncer/commit/7f42e98ac42325168b37f93d61c396d42f9b2165. Use it like this in your `AppServiceProvider`'s `boot` method:

```php
Bouncer::tables([
    'abilities'  => 'my_abilities_table',
    'roles'      => 'my_roles_table',
    'user_roles' => 'role_user',
]);
```

Please test it out and let me know if it works for you.

I should have listened to you right away :grinning:

**Comment by Gummibeer** [comment]
@JosephSilber Just for interest: at the moment everything you add for configuration are methods with parameters. This is coll & ok, but why you don't add a config file, read it in the service provider and call your own methods if the keys are existent in the config file?

**Comment by JosephSilber** [comment]
Because I don't like config files.

**Comment by jonagoldman** [comment]
:+1:

**Comment by vesper8** [comment]
Shouldn't this be part of the readme docs (ability to change table names) as opposed to being hidden in a closed issue
