### ISSUE TITLE
Migration issue. 

### ISSUE THREAD

**Issue by ifarooq** [JosephSilber/bouncer#224]
Hi, After adding bouncer package, when I try to run migration it gives me following error.

I am running following command. 
 
$ php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is
  1000 bytes (SQL: alter table `abilities` add unique `abilities_unique_index`(`name`, `entity_id`, `ent
  ity_type`, `only_owned`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is
  1000 bytes

**Comment by JosephSilber** [comment]
Fixed in `master`.

This fix has not been tagged. To use it now, update your `composer.json` version of `bouncer` to this:

```json
"silber/bouncer": "dev-master#2633721877cae79ad461f3ca06f3f77fb4fce02e"
```

Then:

1. Delete the published migration file.
2. Republish the new one with `php artisan vendor:publish --tag="bouncer.migrations"`.
3. Remigrate using `php artisan migrate:fresh`. **Warning: this will delete all of your data in the DB, so only run this in development.
