### ISSUE TITLE
Forbidding Role Abilities

### ISSUE THREAD

**Issue by jschutt** [JosephSilber/bouncer#231]
Hello!

Can you please help me understand the following scenario? 

1. I create an `admin` role and give it `update-user` and `update-post` abilities.
2. I assign the `admin` role to User A
3. I forbid User A's ability to `update-post`

Should `$userA->getAbilities()` include a record for `update-post`?

I know that he still has the admin role, which includes `update-post`, but if I explicitly forbid the ability, I would expect it to not show up in the list of User A's abilities.

For the record, I've tested this scenario and the `update-post` ability still shows in the `getAbilities()` method, however testing if User A can `update-post` returns `false`.

Thank you 👍

**Comment by JosephSilber** [comment]
The getAbilities() method is a low-level method for getting the ability records assigned to the user. Since the user has been given that ability, getAbilities() will return that ability.

Forbidding an ability does not remove the allowed ability record. If you unforbid() the ability, Bouncer will continue slowing that action.

To get a user's forbidden abilities, you can call $user->getForbiddenAbilities().

When Bouncer checks if a user can perform an action, it first checks the forbidden abilities. If present, the action is denied. Otherwise, Bouncer continues to check the allowed abilities.

**Comment by jschutt** [comment]
Thanks for the explanation!

If I'm understanding correctly, there is not a method that will show me all the users's abilities without including the forbidden ones?

**Comment by JosephSilber** [comment]
Here isn't, and in fact it's impossible.

Imagine you set up the following abilities:

Bouncer::allow($user)->toManage(Post::class);
Bouncer::forbid($user)->to('delete', Post::class);

What would you expect that mythical method to return?

**Comment by jschutt** [comment]
Well, that example is slightly different than what I was originally asking.

In essence, I was asking if an explicit forbid of Ability A would override the implicit granting of Ability A via an assigned role.

**Comment by JosephSilber** [comment]
I understood, but it doesn't make sense for such an implementation to be incomplete.

For your needs, you can manually filter the list of abilities against the list of forbidden abilities.

**Comment by jschutt** [comment]
Related to #232, if I'm needing to have variations off default roles am I better off skipping roles altogether and assigning abilities directly to users instead?

Thanks for your time and willingness to educate me :-)

**Comment by JosephSilber** [comment]
@jschutt it all depends on how much you plan on veering off the standard roles.

If you'll only have tiny variations off of it, you should probably create roles, and add/remove abilities for users on an individual basis.
