### ISSUE TITLE
Entity type / Model type

### ISSUE THREAD

**Issue by jonagoldman** [JosephSilber/bouncer#26]
Having the ability to easily specify an entity type and a entity id is awesome!

```php
Bouncer::allow($user)->to('edit', Post::class);
```
```php
Bouncer::allow($user)->to('edit', $post);
```

The entity class name is saved as a string in the ```entity_type``` column. This is simple and straightforward but what do you thing about moving this column to its own table?

Pros:
- Database normalization.
- Easy to change the entity class name without touching the abilities table.

Cons:
- Additional table relationship to manage.

**Comment by Arcesilas** [comment]
I haven't dived so much in the code, but it seems this is the way polymorphic relations work. So I think it has to be here, not anywhere else.

**Comment by jonagoldman** [comment]
Looks like a Morph Map could fix this issue.
Some people had this issue too and they added to the laravel repo what seems to be an undocumented method to map a string to a class name. See https://github.com/laravel/framework/pull/9839

**Comment by JosephSilber** [comment]
Look at [this Laravel PR](https://github.com/laravel/framework/pull/10147) if you want to use the table names instead of the model class names.

Simply add this to your `AppServieProvider`'s `register` method:

```php
Relation::morphMap([
    App\Post::class,
]);
```

Add all of the models you use into that array (remember to import the `Relation`'s namespace).

This is what I personally do for all my morphing models.
