### ISSUE TITLE
Question about the performance/if this is the correct way to use Bouncer (showing manageable tasks).

### ISSUE THREAD

**Issue by coniurare** [JosephSilber/bouncer#261]
Hi,

sorry if this is the wrong place to ask, but I couldn't find a gitter chat or email list etc.

Thanks for the library it's really easy to work with so far (I'm only evaluating at the moment). But being new to laravel/bouncer and dynamically typed languages where it is harder to "click-through" to see the implementation of methods compared to statically typed languages, I'm wondering about the performance of the way I use Bouncer in a specific method.

For context users can have the following simple roles: 
- admin (allowed to do anything)
- group_owner (can do anything in their group)
- group_member (can manage tasks assigned to them by the group_owner, but nothing else)

I have a html page were a user should be able to see all tasks which they can manage. A admin would see all tasks, a group_owner would see all tasks in their group and a group_member would only see their own tasks.

It's implemented as a extension method on the user model at the moment:

```php
public function getManageableTasks() {
    return Task::get()->filter(function($task) {
        if($this->can('view', $task)) {
            return true;
        }

        return false;
    });
}
```

This works but I'm wondering about the performance of it. Will this make a single SQL query and then filter the resultset locally, or will this make a SQL query for every call to the gate (can)?

**Comment by JosephSilber** [comment]
You are loading every single task from the DB into your PHP application, and then filtering. This is very inefficient.

Due to Bouncer's code-based features (such as ownership etc.), it is not possible to reliably perform this check in the DB directly.

**Comment by garygreen** [comment]
@JosephSilber I've been wondering about performance as well, it doesn't seem terribly efficient.

For instance, when checking for permissions it has to load ALL abilities for a user in order to determine if they have access - if you have hundreds of abilities for users this doesn't seem like an efficient way to check imo.

I was kind of hoping it would just do a DB lookup to get the ability by name, or any abilities which are relevant.

In my our app, we would like to do something like:

```php
Bouncer::allow($user)->to('view-private-pictures', $user2)
```

The above could be run on hundreds of users - basically in our system, you can authorize people to be able to see your private pictures. In theory, a person could authorize hundreds of people - which means they will receive hundreds of abilities. Whenever an ability is checked, it will load in all of those other abilities.

**Comment by coniurare** [comment]
@JosephSilber - thank you for the answer.

**Comment by JosephSilber** [comment]
@coniurare [it won't](https://github.com/JosephSilber/bouncer#cache):

> By default, all queries executed by Bouncer are cached for the current request.

**Comment by JosephSilber** [comment]
@garygreen that is actually a separate issue. For people that don't use single model abilities that much, pulling down all abilities at once is actually better.

I do plan on creating a separate `Clipboard` that only pulls down the relevant abilities for the given query, and swap that out when calling `Bouncer::dontCache()`.
