### ISSUE TITLE
Model UUID support or UUID documentation

### ISSUE THREAD

**Issue by OzairP** [JosephSilber/bouncer#272]
Firstly, thanks for the great package, and the time you put into this.

I am using binary uuid's for my `User` model via https://github.com/spatie/laravel-binary-uuid.

However, I cannot assign a role to a user because `entity_id` only accepts integers. When changed to a string, Bouncer accesses the binary version of the UUID instead of the string representation. Is there anyway to fix this? I know you don't want to support non-integer ID's but documentation for those who want to use non-integer id's would be great:)

Thanks! Let me know if theres anyway I can contribute!

**Comment by JosephSilber** [comment]
Using regular UUIDs works by simply changing the migration and, depending on the DB driver, assigning the UUID in the creating event.

However, binary UUIDs are more involved. Since the Spatie package requires encoding the value whenever you query against it, I don't see how that could possibly work with a generic package like Bouncer.

**Comment by OzairP** [comment]
That sucks 😞. Thank you for the fast reply:).
