### ISSUE TITLE
Upgrading from 0.* to 1.0

### ISSUE THREAD

**Issue by tobias-kuendig** [JosephSilber/bouncer#274]
I have an application in production that is currently using Bouncer 0.1.7 on Laravel 5.2.

In the progress of upgrading this application to Laravel 5.6 I need to upgrade Bouncer as well. What would be the easiest way to do this? 

Looking through the commit history I stumbled upon the `bouncer:upgrade` command that unfortunately got removed in [this](https://github.com/JosephSilber/bouncer/commit/b34520ff9475a133daead4532e689b90cf63cb76#diff-2d162e07be0cf65cc1054b2128c60258) commit. Why was it removed? Will it be replaced by a new upgrade command before 1.0 stable is released?

Thank you very much for your help and your work on this great package!

**Comment by JosephSilber** [comment]
> Will it be replaced by a new upgrade command before 1.0 stable is released?

That's the plan. I removed it because 1.0 itself was going through some schema changes.

---

For now, here's what you can do:

1. Checkout [the commit before the removal](https://github.com/JosephSilber/bouncer/commit/05b00925c7a0bb7bb263c389d578cb30c849a1f6), by setting it up in your `composer.json` file:

    ```
    "silber/bouncer": "dev-master#05b00925c7a0bb7bb263c389d578cb30c849a1f6"
    ```

    ...and run `composer update`.

2. Migrate your tables to include the `scope` column, as outlined in the [beta 5 release](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5) (scroll down to the Breaking Changes section).

3. Update Bouncer's composer version to `v1.0.0-rc.1` and run `composer update` again.

4. Enjoy the weather, the scenery, your family or whatever else makes you happy :heart_eyes:
