### ISSUE TITLE
Feature request - middleware for roles

### ISSUE THREAD

**Issue by acidjazz** [JosephSilber/bouncer#288]
Is it possible yet to have middleware rules for roles? something like 

```php
Route::apiResource('users', 'UserController')->middleware('role:admin');
```

If this is possible let me know how, and I'll PR an example for the readme

**Comment by JosephSilber** [comment]
Creating the middleware is extremely easy. Bouncer intentionally does not ship with such a middleware because, as explained in the docs, checking for roles directly is an anti-pattern. You're much better off creating a broad ability, assigning it to any role that needs it, and check for that ability directly.

**Comment by acidjazz** [comment]
@JosephSilber hah i just realized we've been down this road before with #205 

So then would I just name the ability 'admin' and use it that way? What would your preference be in this situation?

**Comment by acidjazz** [comment]
So the to stick to pattern i should instead create abilities for each endpoint the admin portal can hit, and middleware each with `can:abilitiy` ? ex

```php
      Bouncer::allow('admin')->to('login-as-user');
      Bouncer::allow('admin')->to('delete-content');
```

**Comment by JosephSilber** [comment]
Bouncer::allow('admin')->everything();

Then, use the "can" middleware to check whatever ability you want to check.
