### ISSUE TITLE
Levels - safe to use?

### ISSUE THREAD

**Issue by scottybo** [JosephSilber/bouncer#301]
I've had a careful read through: https://github.com/JosephSilber/bouncer/issues/223

I have a use case where owners of a Team can invite other team members. I'd like the team owner to assign a Role to the user they're inviting, but only at a "Level" at or below the current Team Owners level.

Should I just manage this myself by adding a new column to the Role table (e.g. I could call it: power, authority, privilege etc) and simply do a check to make sure that when an invitation occurs, the Team Owner has the "authority" to set a user to a "lesser" Role authority.

Or is this what Levels is designed to do?

If this feature is going to be deprecated, I'll implement it in a way that works independently from the Bouncer core. Just need to know if possible!

**Comment by JosephSilber** [comment]
> safe to use?

I wouldn't advise anyone starting out with Bouncer now to use levels. I believe they were a mistake to be added in the first place. For now I've decided not to remove them, since some people rely on it. But I would definitely not encourage anyone to use it in a new project.

> is this what Levels is designed to do?

This is not what `level` is designed to do, and if you use this column for your own use, it'll conflict with Bouncer.
