### ISSUE TITLE
Is it possible to get a list of all the model instances a user has access to?

### ISSUE THREAD

**Issue by mitchkramez** [JosephSilber/bouncer#308]
I feel like I've got to be overlooking something, but if I've given `User A` access to a specific instances of a `Listing` model, is there a way to retrieve those `Listings` the user has access to, so I can show a list or something similar?

Thanks!

**Comment by JDias** [comment]
+ just to follow this issue!

**Comment by JDias** [comment]
Hi @mitchkramez im really new to all of this, but i will share what i found so far.

in the abilities you have "entity_id":null,"entity_type":null,"only_owned":0,"scope":null,
so, if i understand correct you want to get the entity_tpye and entity_id of all the abilities of a group of roles (that User A belongsTo)?

**Comment by JDias** [comment]
yes, you can :)

$abilities = $user->getAbilities(); and get the entity_type and entity_id (im not sure how to fill this 2 fields but i really think that was what asked for)

at least for me is enough. (btw, im really impressed with bouncer)

**Comment by JDias** [comment]
Hi again @mitchkramez i think that those fields are not what i first thought, i think you can use the abilities name to reach your desired approach.

like this:

https://voyager.readme.io/docs/permissions

than you just need to do some string manipulation to gather your info.

**Comment by JosephSilber** [comment]
Since Bouncer has many dynamic features that can influence a user's access to a given model (such as [ownership](https://github.com/JosephSilber/bouncer/blob/master/readme.md#ownership) or [policies](https://laravel.com/docs/5.6/authorization#writing-policies)), there's no way to query the DB for all models a user has access to.

If you yourself don't use any of Bouncer's dynamic features, you can create this query yourself based on the subset of Bouncer features that you do use.
