### ISSUE TITLE
Check on parents for model ability

### ISSUE THREAD

**Issue by mix359** [JosephSilber/bouncer#312]
Hi to all,

I'm currently updating a project that is using the bican/roles package for the permission/role, and I'm searching something maintained and with the ability to give a user the permission on a model instance or his children.
I need to give a role/user the permission on something like a post category that can have some sub-categories, so when I'm checking if a user have a permission a category, I need that the system can check on that category and on his parents recursively. 

Does this package can do that? Would be interesting for the future?
In case, I have some ideas in mind on how to do that...

Thanks to all
Cheers
Mix

**Comment by JosephSilber** [comment]
You can use a policy for this:

```php
class CategoryPolicy
{
    public function view($user, $category) {
        return $category->getParents()->contains(function ($category) {
            return Gate::can('view', $category);
        });
    }
}
```

The above assumes a `getParents` method on your `Category` class, which you can easily add.

---

The way Bouncer works is that it integrates directly with the `Gate`. If Bouncer allows an action, your policy won't be called. But if Bouncer doesn't have a direct permission for the action, then your policy will be called.

Here, we're assuming the user doesn't have a direct permission for the given category (otherwise Bouncer would've already allowed it), so your policy is invoked. Within your policy, you check at the gate (which will check with Bouncer) for each of the category's parents. If any of them is allowed, your policy method will return `true`.

**Comment by mix359** [comment]
Sorry for the late reply.
Many Thanks @JosephSilber that sound like what I need :)
Only one thing, that I'm trying to understand: Does this code work recursively? In case no, there any way? So that it will check the parent category recursively until a category allow the permission or there is a parent.

Thanks again!
