### ISSUE TITLE
Migration Pitfalls

### ISSUE THREAD

**Issue by fredrkr** [JosephSilber/bouncer#4]
Dropping the user-table in the migration's down-function is risky. The users-table is included in a clean Laravel install, so most likely it should be left alone.

The keys you use inside the pivot-tables, aren't really keys at all. They're just ints. These should be indeces and foreign keys, referencing the foreign table.

On a nitpickety note, the convention in Laravel, I believe, is to use the table-names, singular, in alphabetical order, as names for pivot-tables. I.e. role_user, ability_role, ability_user.

I also found a typo, which seems to be significant. The HasRolesAndAbilities trait, has this:
```php
public function abilities()
{
    return $this->belongsToMany(Ability::class, 'user_Abilities'); // this should be user_abilities
}
```

Thanks for this package :-)

**Comment by JosephSilber** [comment]
1. The users table shouldn't be in Bouncer's migrations at all. [Fixed](https://github.com/JosephSilber/bouncer/commit/a5bba090190104307e6bdba25eb7eba58a4ffc91).
2. I've added indexes and foreign keys where applicable. https://github.com/JosephSilber/bouncer/commit/44a888139ba59539ed76ab8f5b4ab8b1bb446b56.
3. I dislike Laravel's convention. It's good as a default, but it's not very descriptive. That's why Eloquent lets you override it :)
4. The typo has been [fixed](https://github.com/JosephSilber/bouncer/commit/90be27ff8931e33b129b6ac094b0a13a7452ab31) as well.

Thanks for the amazing feedback. Keep it coming!

**Comment by mstaack** [comment]
great!
