### ISSUE TITLE
problem in route #2

### ISSUE THREAD

**Issue by AndrewOzarko** [JosephSilber/bouncer#414]
Hello everybody. I use bouncer in laravel. It is a perfect library(bouncer). I have a trouble in checking forbidden abilities.
I forbidden the User with id 1 to view contact  with id 2, but it does not work. 
    Route::get('contacts/{id}', 'ContactController@getContactById')
        ->name('contacts.view')
        ->middleware('can:view,id');

I have an error "message": "Class '2' not found". I understand why, but maybe i cannot understand how to do normal checking. Please help me.

**Comment by JosephSilber** [comment]
You need to use [form model binding](https://laravel.com/docs/5.8/routing#route-model-binding), so that the `can` middleware can find your model:

```php
Route::get('contacts/{contact}', 'ContactController@getContactById')
     ->name('contacts.view')
     ->middleware('can:view,contact');
```

```php
class ContactController
{
	public function getContactById(Contact $contact)
    {
        // Laravel's form model binding will automatically fetch the contact for you...
    }
}
```

Here's a little more information about the `can` middleware: https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#the-can-middleware
