### ISSUE TITLE
Implements Bouncer on existing platform

### ISSUE THREAD

**Issue by Mindexperiment** [JosephSilber/bouncer#452]
Hi guys,
I would like to implements Bouncer package on an existing platform still in production stage.

Can somebody, please, give me some best-practices on how to setup the Bouncer for the existing records? I have seed 4 roles: superadmin, admin, moderator and business.

Now, I need to assign each existing users with a role but don't know how to.. then I think that assign the roles to new user can be done inside controllers. And, if I want to have an admin that assign roles to users like in an organization?

Thank you

**Comment by JosephSilber** [comment]
Thanks for your interest in Bouncer.

Detailed help with your specific application is out-of-scope for these GitHub issues.

I would suggest you ask on [stackoverflow](https://stackoverflow.com]. You should also provide much more information about your current setup, because it won't be possible to help you without additional details.
