### ISSUE TITLE
Possible to query models for access?

### ISSUE THREAD

**Issue by grenadecx** [JosephSilber/bouncer#482]
Is it possible to query a model based on it's access for a given user? For example a user could own it's own models, but it could also have been given access to a specific model, example below

```
Bouncer::allow($user1)->toOwn(Posts::class);
Bouncer::allow($user1)->to('view', $post2);
```

```
// Append this query to somehow get all posts that use has view access for
$posts = Posts::get();
```

Would it be possible to fetch all Posts based on if the user has access to view it? If that's not currently possible, I think it's something that would be really useful and make a lot of sense. 

If it isn't currently possible, what would be the best way to acheive something like this in the meanwhile?

Might be be same questions asked in #461

**Comment by ldiebold** [comment]
Following.

**Comment by therealmjk** [comment]
@JosephSilber

**Comment by Ralla** [comment]
Subscribed, this would be a neat feature.

**Comment by grenadecx** [comment]
This is really a necessity. Giving users access to stuffs but not being able to query that access when retreiving from database is really bad. But I don't expect any answers on this tho.

While I love this package, and I love that it supports setting permissions with abilities and models. but this is a huge issue in my opinion.

**Comment by bpuig** [comment]
I think there is a big issue with this and `ownedVia()`, since in ownedVia you can do whatever logic you want as long as it returns `true` or `false`. To check ownedVia against one record is not much of a problem, but, how do you apply the logic against all the table?

Me myself have in my project code:

```
Bouncer::ownedVia(CustomerPaymentMethod::class, function ($customerPaymentMethod, $user) {
    return $customerPaymentMethod->customer_id === $user->customer->id;
});
```
And this is a simple one, imagine one with a subquery, and then the id checked against a collection.

You'd need to check every record on the table to be matched against that function, and that raises many issues. I think it's not possible to retrieve access based on a model in the way this package is structured. You'd need to make it more restrictive to simple relationships, hence removing ownership via.

**Comment by grenadecx** [comment]
You've probably right. But I could live something simplified that ignored the ownvia function or that it was removed to make this possible.

Right now, let's say you have access to 10000 records, but I only want to retrieve 50 (for pagination purposes and less data to deal with), there's no way to do that. you'd need to get all the records, it could be a million for all I know. Loop them and then filter out what I don't have access too. There's no way to deal with a subset of what I have access too, and that's a huge problem tbh.

**Comment by grenadecx** [comment]
I don't expect any answers on this one. Closing it.
