### ISSUE TITLE
Wrong Entity when allow on Role Model

### ISSUE THREAD

**Issue by CreativeBulma** [JosephSilber/bouncer#489]
Hi,

When I create following Role Model abilities:
```php
\Bouncer::ability()->firstOrCreate([
    'name' => 'list',
    'title' => 'List roles',
    'entity_type' => Role::class,
]);

\Bouncer::ability()->firstOrCreate([
    'name' => 'read',
    'title' => 'Read roles',
    'entity_type' => Role::class,
]);
```

Entries in DB have the right entity_type <code>Silber\Bouncer\Database\Role</code>

When allowing a specific role to list and read Role Model with following command:
```php
\Bouncer::allow('administrator')->to(['list', 'read'], Role::class);
```

Its seems not finding existing abilities and create new ones with entity_type <code>roles</code>.

After having a look into source code it seems that when using <code>->forModel($entity, true)</code> into <code>findAbility</code> method from <code>FindsAndCreatesAbilities.php</code> file the model class name is retreived using <code>$entity->getMorphClass()</code> which returns <code>roles</code> instead of the real entity class name.

How can I fix it ?

regards,

**Comment by grenadecx** [comment]
By the looks of it's because this project uses morphMap and I don't see a way to turn it off:

```
\Bouncer::ability()->firstOrCreate([
    'name' => 'read',
    'title' => 'Read roles',
    'entity_type' => Role::class,
]);
```
Instead of using Role::class, which won't work when you use morphmap, I suggest you use either "roles" directly or take advantage of the getMorphClass function of the Eloquent model. But because that isn't static, you would need to do something like:

```
\Bouncer::ability()->firstOrCreate([
    'name' => 'read',
    'title' => 'Read roles',
    'entity_type' => (new Role)->getMorphClass(),
]);
```
Just to be clear, since bouncer uses morphmap, storing the morphmap name in the entity_type should be the correct solution.

The code responsible for the morhmap comes from the src/Database/Models.php

```
    public static function updateMorphMap($classNames = null)
    {
        if (is_null($classNames)) {
            $classNames = [
                static::classname(Role::class),
                static::classname(Ability::class),
            ];
        }
        Relation::morphMap($classNames);
    }
```

**Comment by CreativeBulma** [comment]
Thanks for the clarification about morphMap.

Unfortunately <code>roles</code> is not an Entity_type so Bouncer is not consistent in its way of working.

Why creating ability with <code>Role::class</code> works (add the right entity class name in DB) and retreiving it when adding ability to a role is not working.

How can I be sure authorization will work when I try to check if user is able to read Role::class for example ?

Internal entity types (which are extendable - Boucner provides a way to customize them) should be managed as any other entity types.

**Comment by grenadecx** [comment]
First of entity_type and entity_id is based on eloquent polymorphic relation, so supporting morhmap is curcial. But I agree that there should be a way to turn off the morphmap from bouncer if that's not desired.

For example I have an ability that allows users to manage all roles, and if if I take that abilities entity_type and put it into:

```
Bouncer::allow($role)->toManage($ability->entity_type);
```

It's not gonna work because entity_type is set to roles instead of the classname with namespace. 

I would suggest an option to turn off the morphmap, but even when it's on, like my example above, it should check inside the morphmap before adding it and use that translation, now it will just error me because it wont find "roles" as a class.

To circle back your authorization question tho, I don't think there's a problem when it comes to morhpmap there, or at least from what I can tell.

**Comment by JosephSilber** [comment]
I wrote a bit about morph maps here:

https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map
