### ISSUE TITLE
Class 'App\User' not found in Laravel 8

### ISSUE THREAD

**Issue by amtzm93** [JosephSilber/bouncer#539]
## Problem
When you trying to install Bouncer for Laravel 8, the autoload discovery throws the next error

![image](https://user-images.githubusercontent.com/25335245/96068192-02693d00-0e61-11eb-9487-257d89eeaff7.png)

## Solution 
In **Laravel 8**, the models are located in the path `./app/models`, so the User Model path would be `./app/models/User.php`
The root of the error is in **line 6** in the file **Models.php** (vendor/silber/bouncer/src/Database/Models.php) 
```php
use App\User;
```
So the fix would be 
```php
use App\Models\User;
```

**Comment by JosephSilber** [comment]
I just tried this in a brand new installation of Laravel 8, and I didn't get any error:

![image](https://user-images.githubusercontent.com/1403741/96207877-467c4080-0f3a-11eb-832f-b35db680320f.png)

---

The reason it's supposed to work is because Bouncer automatically registers your auth provider's user model:

https://github.com/JosephSilber/bouncer/blob/05f030bb88d9a26d6cd9c580f883a0dd0d9c767f/src/BouncerServiceProvider.php#L133-L142

As you can see, Laravel 8 now has that `model` key set to `App\Models\User::class`: 
https://github.com/laravel/laravel/blob/6bfe68365d0ab1301dfae87867814048440d6a78/config/auth.php#L71

Are you sure that's correctly set in your app?
