### ISSUE TITLE
How to allow users to own themselves?

### ISSUE THREAD

**Issue by Synchro** [JosephSilber/bouncer#570]
I want users to be treated as owners of their own records, so they can edit their own data but not anyone else's. How should I assign this ability? I'm currently looking at:

        Bouncer::ownedVia(
            User::class,
            function ($user, $owner) {
                return $user->id == $owner->id;
            }
        );

or is there some shortcut, as I'd imagine this is a common requirement?

**Comment by JosephSilber** [comment]
Simply passing in `'id'` should work:

```php
Bouncer::ownedVia(User::class, 'id');
```

**Comment by Synchro** [comment]
Thanks

**Comment by huy-tran** [comment]
Hi,

Where should I put this code and how to check the permission.

My code is as following:
`Bouncer::allow($user)->toOwn(User::class)->to(['read', 'update']);`

And when checking in the authorization:
`Bouncer::can('update', User::class);`

The authorization always return **false** unless I set **only_owned** to false within **abilities** table which is not ideal because I don't want the user to edit others.

Thanks in advanced.

**Comment by JosephSilber** [comment]
In your `AppServiceProvider`'s `boot` method, add this line:

```php
Bouncer::ownedVia(User::class, 'id');
```

**Comment by huy-tran** [comment]
Thanks @JosephSilber ,

I added that to the ServiceProvider and also adjust the authorize method in the controller to `request()->user()->can('update', $user)` and it works for me.

Thanks again!
