### ISSUE TITLE
suggestion: add description column to ability table

### ISSUE THREAD

**Issue by xciser77** [JosephSilber/bouncer#86]
I would like to have a description column in the ability table so you can make a small description about the ability in the cms or page we are making.

Now I can only make a small ability 'tag'

**Comment by renanBritz** [comment]
Since you're building a CMS, which could eventually support multiple languages, you could try storing the ability descriptions in a language file.

**Example:** resources/lang/en/abilities.php

**abilities.php structure:**

```php
<?php
    return [
        'create-article' => 'Post new articles in the blog',
        'name' => 'description',
        //...
    ];
```

And then you would match the ability name with the description name in the translation file.

```php
$ability = Bouncer::ability()->first(); //Example

$abilityName = $ability->name;

$description = trans("abilities.{$abilityName}");
```

[Laravel Localization](https://laravel.com/docs/master/localization).

I hope this helps.

Regards!

**Comment by JosephSilber** [comment]
You can edit the published migrations however you like. Simply add a description column and you're good to go. Nothing stopping you there.
